name: 'Bistecglobal Hackathon Evaluate'
description: 'Evaluate Bistecglobal hackathon'
branding:
  icon: 'award'
  color: 'green'
inputs:
  base-app-url:
    description: 'Application UI Url'
    required: true
    default: ''
  base-api-url:
    description: 'Application API Url'
    required: true
    default: ''
  github-token:
    description: 'Github token'
    required: true
    default: ''
  sonar-token:
    description: 'Sonar token'
    required: false
    default: '7a67705cbaccbf63ce18a2b40b9904b9df34c36e'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - run: echo using API ${{ inputs.base-api-url }}.
      shell: bash
    - run: echo using web ${{ inputs.base-app-url }}.
      shell: bash
    - id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ inputs.sonar-token }}
    - name: Setup and run tests
      run: |
        export CYPRESS_BASE_URL=${{ inputs.base-app-url }}
        export CYPRESS_API_BASE_URL=${{ inputs.base-api-url }}
        test.sh
      shell: bash
    - run: goodbye.sh
      shell: bash